### ISSUE TITLE
Processing of HTTP Request expects RequestInterface

### ISSUE THREAD

**Issue by mihazs** [railt/railt#180]
### Expected Behavior
Request processed with success

### What happens instead?

The request method didn't accept the Railt\Http\Provider\GlobalsProvider,
When i execute a query, this error are throwed:
```
Fatal error: Uncaught TypeError: Return value of Railt\Foundation\Connection::requestsToIterable() must be iterable, object returned in /app/vendor/railt/railt/src/Foundation/Connection.php:179 Stack trace: #0 /app/vendor/railt/railt/src/Foundation/Connection.php(148): Railt\Foundation\Connection->requestsToIterable(Object(Railt\Http\Provider\GlobalsProvider)) #1 /app/controllers/GraphqlController.php(21): Railt\Foundation\Connection->request(Object(Railt\Http\Provider\GlobalsProvider)) #2 [internal function]: App\Controllers\GraphqlController->main() #3 [internal function]: Phalcon\Mvc\Micro\LazyLoader->__call('main', Array) #4 [internal function]: Phalcon\Mvc\Micro\LazyLoader->callMethod('main', Array, NULL) #5 /app/bootstrap/handler.php(30): Phalcon\Mvc\Micro->handle() #6 /app/web/index.php(4): require('/app/bootstrap/...') #7 {main} thrown in /app/vendor/railt/railt/src/Foundation/Connection.php on line 179
```

### Description
I've done this in my application, following the documentation in Readme
```php
$app = new Application();
        $app->configure(Composer::fromDiscovery())
            ->connect(File::fromPathname('../resources/schema.graphqls'))
            ->request(new GlobalsProvider())
            ->send();
```

### Steps To Reproduce

Just execute a query using the function in description

### Suggestion
The request method in ConnectionInterface expects RequestInterface|RequestInterface[] as parameter, and the globalprovider (or any provider) didn't implements this interfaces. The providers must implement the request interface.
We can see this in:
```php
declare(strict_types=1);

namespace Railt\Foundation;

use Railt\Http\Identifiable;
use Railt\Http\RequestInterface;
use Railt\Http\ResponseInterface;

/**
 * Interface ConnectionInterface
 */
interface ConnectionInterface extends Identifiable
{
    /**
     * @param RequestInterface|RequestInterface[] $requests
     * @return ResponseInterface
     */
    public function request($requests): ResponseInterface;

    /**
     * @return void
     */
    public function close(): void;
}

```
### Environment

- Railt Version: dev-master
- PHP Version: 7.2

**Comment by SerafimArts** [comment]
```
$app = new Application();
        $app->configure(Composer::fromDiscovery())
            ->connect(File::fromPathname('../resources/schema.graphqls'))
            ->request(new Factory(new GlobalsProvider())) // <<----
            ->send();
```

The reason is that the "provider" simply provides data from some source, in this case global GET and POST vars. And they still need to be properly processed and turned into a collection of Request objects.

**Comment by SerafimArts** [comment]
I corrected the readme, following the latest changes. Thanks for feedback 👍
